### ISSUE TITLE
Starter Issue

### ISSUE THREAD

**Issue by Aregluss** [L-S-Farlee/JavaLibrary#1]
Hi,

Wanted to start off with saying good job overall, I'm no sure how long you've been coding in Java or how much experience you have, but overall nice work.

I personally haven't GitHub much for opening issues and reviewing code. 
One thing is, I would suggest you learn on how to use pull requests going forward. Should learn what they are, why they're used, and if you don't limitedly merge changes I can make comments on the set of changes before you put the code into master.
(Although I really recommend this, if you feel like this isn't your focus rn, no worries, you can give me periodic updates when you make changes and I can take a look)

I'll open an issue w/ file name + #, and include line numbers for you as I write things up.
I'll do my best to tell you why I'm leaving the comments. I encourage you to first think why I'm saying it and then always welcomed to question me why I say things or why I point things out. 
Reach out to me over Reddit if you'd like.
(Mark this done once you've read it 👍 )

**Comment by L-S-Farlee** [comment]
Thank you so much for the feedback and suggestions in these issues, I've really enjoyed returning to this project to fix the issues you've found. I apologize for taking a few months to get to these, 2020 went from "very rough" to "nightmare" for me shortly after you first posted these issues, and I wasn't able to get right to work on them. 

I'll be working to fix the issues in batches, starting with pull request #14. Thank you again for the help!
