### ISSUE TITLE
Round 1 of Issues

### ISSUE THREAD

**Issue by Aregluss** [L-S-Farlee/JavaLibrary#13]
Honestly you've done a great job overall, hope you take these comments as an opportunity to learn as well!
If this is the first issue you're reading I recommend you start form bottom up instead.

Hope you the best, ping me over Reddit once you're done or have questions/comments on the issues I've opened. 
Otherwise I'll periodically check here to see what updates you've made and what you've marked complete.

HF

**Comment by L-S-Farlee** [comment]
Once again, I truly appreciate your detailed feedback and useful suggestions. Revisiting this project to implement your ideas was a very useful learning experience, thank you for your time helping with this project!
