### ISSUE TITLE
UserAccount.java Issue 1

### ISSUE THREAD

**Issue by Aregluss** [L-S-Farlee/JavaLibrary#9]
I see this is an abstract class and I see how you use it. I'd however recommend that you add a constructor to it.
And yes it sounds strange at first, and yes you'll never use the constructor directly to create an instance of UserAccount.

Something like
```
public UserAccount (str name, str id, str holderId)
{
  this.name = name;
  this.id = id;
  .
  .
}

```
If you go this issue #10 , you'll see why a constructor is useful.
[StackOverflow link you should read the top answer](https://stackoverflow.com/questions/260666/can-an-abstract-class-have-a-constructor)

**Comment by L-S-Farlee** [comment]
Very good suggestion, I've updated the code for UserAccount to create a constructor for it.

Fixed in #15.
